# resource.toml
type = "js"
main = "npc/server/server.js"  # Pfad zur Server-Datei (relativ zum Ressourcen-Root)

name = "foodtruck"
version = "1.0.0"
author = "Günji"

[client-files]
# Keine Client-Dateien? Lass es leer oder entferne den Block
files = []  

[server-files]
files = [ "npc/server/server.js" ]  # Relativer Pfad zur Server-Datei

dependencies = [ "altv" ]